version: "3"
services:
  django:
    build: .
    volumes:
      - ./:/var/server/
    working_dir: /var/server/
    ports:
      - "3000:3000"
    command: sh -c "python manage.py runserver 0.0.0.0:3000"
  web:
    image: node:14
    volumes:
      - ./client:/code
    working_dir: /code
    ports:
      - "8080:8080"
    command: sh -c "npm run serve"
