# Generated by Django 3.2.4 on 2021-07-03 19:32

from django.db import migrations, models
import django.db.models.deletion
import expo_agency.models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0002_alter_touractivity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='idcard',
            field=models.CharField(help_text='DNI/IDCARD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='local_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[expo_agency.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[expo_agency.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='touractivity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='expo_agency.product'),
        ),
    ]
