# Generated by Django 3.2.4 on 2021-07-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0003_auto_20210703_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tour'), (2, 'Ubicacion')], default=1, help_text='Tipo de tour o producto'),
        ),
    ]
