# Generated by Django 3.2.4 on 2021-07-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0002_product_image'),
        ('expo_agency', '0003_auto_20210703_1932'),
    ]

    operations = [
    ]
