# Generated by Django 3.2.4 on 2021-07-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0004_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion')),
                ('deleted_at', models.DateTimeField(editable=False, help_text='Fecha de eliminacion, nulo en caso aun no esta eliminado', null=True)),
                ('image', models.ImageField(help_text='Imagenes de galeria para producto', upload_to='product-galery')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expo_agency.product')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
