# Generated by Django 3.2.4 on 2021-07-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0006_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
    ]
