# Generated by Django 3.2.4 on 2021-07-14 20:29

import django.contrib.postgres.validators
from django.db import migrations, models
import expo_agency.models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0007_alter_productimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3, help_text='En el rango de 1 a 5 estrellas', max_digits=2, validators=[expo_agency.models.validate_positive, django.contrib.postgres.validators.RangeMinValueValidator(0), django.contrib.postgres.validators.RangeMaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lugar'), (2, 'Tour')], default=1, help_text='Tipo de tour o producto'),
        ),
    ]
