# Generated by Django 3.2.4 on 2021-07-14 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expo_agency', '0009_auto_20210714_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(help_text='El usuario relacionado al cliente participante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(help_text='Nombre de la ubicacion del destino, la direccion', max_length=255, null=True),
        ),
    ]
