# Generated by Django 3.2.4 on 2021-07-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0011_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='expo_agency.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='expo_agency.product')),
            ],
        ),
    ]
