# Generated by Django 3.2.4 on 2021-07-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0012_productadvice_productservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductServices',
            new_name='ProductService',
        ),
    ]
