# Generated by Django 3.2.4 on 2021-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0013_rename_productservices_productservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadvice',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
