# Generated by Django 3.2.4 on 2021-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0014_auto_20210722_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='request_message',
            field=models.TextField(blank=True, help_text='Mensaje adiciona de solicitud', max_length=1000, null=True),
        ),
    ]
