# Generated by Django 3.2.4 on 2021-07-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expo_agency', '0004_merge_0002_product_image_0003_auto_20210703_1932'),
        ('expo_agency', '0015_alter_reserve_request_message'),
    ]

    operations = [
    ]
