# Generated by Django 3.2.4 on 2021-07-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programactivity',
            name='activity',
            field=models.CharField(help_text='el texto de la actividad, puede usar $contactName y $programSlug', max_length=255, null=True),
        ),
    ]
