# Generated by Django 3.2.4 on 2021-07-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_programactivity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dni',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
