# Generated by Django 3.2.4 on 2021-07-16 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_alter_contact_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion')),
                ('deleted_at', models.DateTimeField(editable=False, help_text='Fecha de eliminacion, nulo en caso aun no esta eliminado', null=True)),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('reviewed_at', models.DateTimeField(help_text='Fecha de entrada revisada', null=True)),
                ('type', models.PositiveSmallIntegerField(default=1)),
                ('patern_annotation_id', models.PositiveIntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
