# Generated by Django 3.2.4 on 2021-07-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='program',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='notes.program'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='patern_annotation_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de entrada revisada', null=True),
        ),
    ]
